#+title: Notes

* System architecture
** Google drive
Good shared filesystem for this
** Hosting systems
- amazon Lightsail - Probably use this
  seems like the best simple option, giving a full server
- amazon ec2
  - possibly could be cheaper? seems unlikely to be though since it is more geared towards higher scale computing requirements
- Me, over summer
  - Use my old computer to host development while working on the web site...
  Possibly I can set this up to export an image and use that for lightsail? this would speed up the start process
** Calendar
Would probably be easier to set up a specific calendar server for the bmes events which can be written to and accessed by other more easily. This would also allow for a button or link which would open someone's calendar app and add this to their calendar
** Discord event bot
Would post information to the discord whenever the calendar is updated, using the central source of event info
* Features
** Centralize event notification
One place to submit all information for events. Submissions can come from the [[Member Portal]]
- distribute through a bot to discord, update a google calendar, send to VPI for newsletter
** Feedback form
- For Officer info, attach to the [[Member Portal]], otherwise have a google form (both should be anonymous, but for officer board we would want to limit to officers)
** Instagram integration
web site should have embedded Instagram feed showing latest posts somewhere?
** Member Portal
This is likely the most ambitious of all of the features, since it would require user and account information. (can use google for authentication? not sure...)
*** Officer Feedback
Feedback forms for e-board, which will probably default to anonymous, but could have a non anonymous option built-in
*** Event Posting
System for officers to add and upload event posters, dates, and information where they will be pushed to a discord bot and the shared BMES google calendar
- Should this also post elsewhere? Tell social media chair? Newsletter?
- Make sure that this works with the workflow of everyone else
- Should sub leads have permissions here? So officers don't need to do everything
Note that sub-leads will need access to this portion of the Member portal
*** Member interaction somehow?
* Website backend outline
** Dynamically loaded Member content
Export officer pictures and info to folder and JSON file, from which JavaScript can load officer information for each officer and update each webpage. Should work for every member associated with bmes which will need a webpage or information about them on the website, since this list will roll-over every year and updating manually is a bad idea
** Instagram API query
#+PROPERTY: Priority LOW
Gets most recent Instagram posts
** Post most recent events on main page
Store all event data in database and query for any upcoming events to be posted to main page
- Possibly with a timer on this, so that events only appear when they are within a certain time-frame?
* Website Structure
** Main Page
*** Get Involved
Small section of text followed by link to getting involved page
*** Upcoming events
dynamically load events
*** Major events
Div section for major events that are upcoming which can link to eventbrite, volunteer sign-up, and other important info for the major events, which can pop up dynamically whenever the event is getting close. This should be on top of Upcoming events
** Get involved page
*** Upcoming GBM Info :dynamic:
*** Links and info about committees
**** What committees do :static:
**** Who is on committee and when/where meetings :dynamic:
*** Submit feedback
General Body feedback form link
*** Officers :dynamic:
List of all current officers
** Committees :dropdown:
*** New Student Committee
*** Outreach Committee
*** Project Team
*** Cell Team :unfinished:
*** MID Planning Committee
*** Lab Expo Planning Committee
*** BE-Day Planning Committee
** Major Events :dropdown:
*** BE-Day
*** Medical Innovation Day
*** Lab Expo

* Further Ideas?
** Bmes events integration
- Assassins ranking tab
Other competitions can be listed somewhere on the website

* Dev overview for deployment
** Server Backend
*** Django
This is a python web framework which should be able to handle everything for the web application based portion of the website (probably mostly the member portal). It can interact with a sql database, where I assume we will store the internship data, and can also manage forwarding based on permissions. It can also handle the more basic aspects such as webpage templating
*** Google oAuth SKD
Integration with this will allow for user authentication. The free version will allow up to 50,000 users if we only want name and email (also one or two other things I don't think we will need) so this should be enough
*** SQL (postgres)
SQL. Need I say more?
** Fontend
*** DONE Identify frontend
This portion should just be for making the website more easily. I don't think(?) any dynamic html building will be nessesary as django templating hand handle all of this, but wil need to write css 🤮. Possibly also JS for internship database, which will want search and filter operations. (though Django may have pre-built templates for that part). If we want more fun things than JS might be nessesary
*** JavaScript
For most of the site this won't be that difficult, but for the member portal fairly extensive interaction will be needed. Mostly this should just be for form submissions, most of which can be handled by the backend, but for the database interaction this will be more complex, as that will need to be displayed on the frontend. I may not need to write this portion though, so we will have to see
*** TODO DataBase interaction
Somehow there needs to be a system for frontend user to interact with the intern database. Not sure what tools will help with this, but should find some?
- It is possible (even likely) that django will have an interface for this. Look into it
* Django Scheme
** App list
*** Main website
Mainly static
**** Views
***** Home (Project root)
***** Committees :dropdown:
 - set up dynamicaly and serve the same template page? This may be an issue if Committees want more specific things on their webpages
***** Principle Members
***** Events
****** TODO Better to template these pages or have each individual?
***** Get involved
*** Member portal
**** Views
***** Home
***** Internship database
***** Account settings?
*** Officer/sublead console
This might get built out of the native django admin console, have to see how easy to use I can make that and with what permission schemes. Ideally use oAuth for all login, so have to see if django admin supports that
*** Eboard console
- Fold into officer console and just allow elevated pemissions?
** Models
Note: ensure that you use database accessors that use the .get function for return values, to ensure that Does not exsit errors are returned in all cases where this is true
*** Events
This will also need to be accessed by the main section of the webstite, for content loading. Should be modified through the Officer/Sublead console
*** Internship Database
**** TODO Check what kinds of data is stored here so you can scheme it
***** attrs
- names
- links
- due date
Also should probably refresh on sql schema diagrams for documentation
