#+title: README

* Intro
Here is the repository for hosting what will hopefully be the website for BMES for many years to come. It contains all of the source code (though none of the data) for the BMES website, BMES member portal, and the BMES admin console. The entire backend is written with the django library (Yay python!), for which you can find documentation [[docs.djangoproject.com][here]]. It should be fairly easy to learn (I recommend starting with the tutorial, but the overview also provides a good outline of how it works). In the [[./dependencies][dependencies]] directory, you can find the yml file specifying the packages for the development environment, which should be a mirror for the one running the web server (I would also recommend using [[/docs/getting-started/miniconda/main][miniconda]] or [[https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html][mamba]] to manage python environments, and keep a mirror of the development environment for when you work on the website). Be sure to update this file whenever you add a dependency to the project. All of the notes I took during development can be found in the [[./notes.org][notes.org]] file, which should hopefully provide a good outline of what I was thinking if you want to know why something was done in a specific way (my [[./todo.org][TODOS]] might also help with this)
